package com.kesmarki.inticky.ticket.enums;

/**
 * Enumeration for comment types
 */
public enum CommentType {
    /**
     * Public comment visible to customer
     */
    PUBLIC("Public", "Visible to customer and agents"),
    
    /**
     * Internal comment visible only to agents
     */
    INTERNAL("Internal", "Visible only to agents and administrators"),
    
    /**
     * System generated comment
     */
    SYSTEM("System", "Automatically generated by the system"),
    
    /**
     * Status change comment
     */
    STATUS_CHANGE("Status Change", "Comment related to status change"),
    
    /**
     * Assignment change comment
     */
    ASSIGNMENT("Assignment", "Comment related to assignment change"),
    
    /**
     * Priority change comment
     */
    PRIORITY_CHANGE("Priority Change", "Comment related to priority change"),
    
    /**
     * Category change comment
     */
    CATEGORY_CHANGE("Category Change", "Comment related to category change"),
    
    /**
     * Resolution comment
     */
    RESOLUTION("Resolution", "Comment providing resolution details"),
    
    /**
     * Escalation comment
     */
    ESCALATION("Escalation", "Comment related to ticket escalation");

    private final String displayName;
    private final String description;

    CommentType(String displayName, String description) {
        this.displayName = displayName;
        this.description = description;
    }

    /**
     * Get display name for comment type
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Get description for comment type
     */
    public String getDescription() {
        return description;
    }

    /**
     * Check if comment is visible to customer
     */
    public boolean isVisibleToCustomer() {
        return this == PUBLIC || this == STATUS_CHANGE || this == RESOLUTION;
    }

    /**
     * Check if comment is system generated
     */
    public boolean isSystemGenerated() {
        return this == SYSTEM || this == STATUS_CHANGE || this == ASSIGNMENT || 
               this == PRIORITY_CHANGE || this == CATEGORY_CHANGE || this == ESCALATION;
    }

    /**
     * Check if comment is user generated
     */
    public boolean isUserGenerated() {
        return this == PUBLIC || this == INTERNAL || this == RESOLUTION;
    }

    /**
     * Check if comment represents a change
     */
    public boolean isChangeComment() {
        return this == STATUS_CHANGE || this == ASSIGNMENT || 
               this == PRIORITY_CHANGE || this == CATEGORY_CHANGE || this == ESCALATION;
    }

    /**
     * Get icon for UI display
     */
    public String getIcon() {
        return switch (this) {
            case PUBLIC -> "💬";
            case INTERNAL -> "🔒";
            case SYSTEM -> "🤖";
            case STATUS_CHANGE -> "📊";
            case ASSIGNMENT -> "👤";
            case PRIORITY_CHANGE -> "⚡";
            case CATEGORY_CHANGE -> "📂";
            case RESOLUTION -> "✅";
            case ESCALATION -> "⬆️";
        };
    }

    /**
     * Get color code for UI display
     */
    public String getColorCode() {
        return switch (this) {
            case PUBLIC -> "#2196F3";        // Blue
            case INTERNAL -> "#FF9800";      // Orange
            case SYSTEM -> "#9E9E9E";        // Gray
            case STATUS_CHANGE -> "#4CAF50"; // Green
            case ASSIGNMENT -> "#9C27B0";    // Purple
            case PRIORITY_CHANGE -> "#F44336"; // Red
            case CATEGORY_CHANGE -> "#00BCD4"; // Cyan
            case RESOLUTION -> "#8BC34A";    // Light Green
            case ESCALATION -> "#FF5722";    // Deep Orange
        };
    }
}
